changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Added
      labels:
        - 'Type: Enhancement'
    - title: Changed
      labels:
        - 'Type: Maintenance'
    - title: Deprecated
      labels:
        - 'Type: Deprecation'
    - title: Removed
      labels:
        - 'Type: Removed'
    - title: Fixed
      labels:
        - 'Type: Bug'
    - title: Security
      labels:
        - 'Type: Vulnerability'
    - title: Other
      labels:
        - '*'